USE clap_lang;
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (1,"Good morning!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (2,"[The question marker, if it exists]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (3,"Do you speak?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (4,"Do you speak English?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (5,"Excuse me, do you speak English?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (6,"No");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (7,"I [The 1st person singular pronoun]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (8,"I speak");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (9,"I speak English [I understand the language]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (10,"I don’t speak English");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (11,"I don’t speak");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (12,"I am going");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (13,"Six or seven");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (14,"Many food places");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (15,"Eight");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (16,"Or nine");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (17,"The food place is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (18,"It's on the left");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (19,"It's to the left of the school");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (20,"I go, I don’t go");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (21,"I am not going");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (22,"Yes, it is delicious");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (23,"Are you also going to the restaraunt?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (24,"Okay");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (25,"No, I don't have money");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (26,"I don't have money");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (27,"I have it, I don’t have it");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (28,"No, no, 5 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (29,"That's fine / enough");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (30,"I have 50 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (31,"I don’t have 50 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (32,"Ten");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (33,"[The response to a greeting in the morning]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (34,"I am");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (35,"Be, to [the verb]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (36,"You are");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (37,"You are not");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (38,"I am not");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (39,"Malian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (40,"American");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (41,"Nigerian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (42,"Togolese");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (43,"I am not American");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (44,"I am Malian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (45,"Yes");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (46,"I am fine [response to “How are you?”]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (47,"It’s fine [response to informal “How is it?”]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (48,"And you?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (49,"also");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (50,"You also");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (51,"Yes, I am Malian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (52,"Sit down");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (53,"Please, sit down");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (54,"Goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (55,"Bye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (56,"I'm also fine");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (57,"You speak Bambara");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (58,"You speak Bambara very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (59,"Thank you");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (60,"Thank you [broken down word by word]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (61,"Thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (62,"I am American");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (63,"Are you Malian?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (64,"Are you a(n)[name of a person speaking Target Language]?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (65,"Excuse me, are you a(n) [name of a person speaking Target Language]?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (66,"Oh, you speak Bambara!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (67,"No, you speak a lot!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (68,"A lot");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (69,"A little");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (70,"How are you?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (71,"Please, slowly");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (72,"Say it again");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (73,"Please, say it again");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (74,"I don’t understand");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (75,"Please, I don’t understand");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (76,"I understand");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (77,"Madam, please, I don’t understand, say it again");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (78,"Madam, sit down");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (79,"The market is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (80,"Is where");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (81,"Is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (82,"The bus station is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (83,"The bank is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (84,"Yes, there is a hotel here");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (85,"The hotel is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (86,"It is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (87,"You speak well");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (88,"What is your name?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (89,"Name");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (90,"Your");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (91,"Is what?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (92,"Are you a teacher?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (93,"My name is Amadou");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (94,"And you, what is your name?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (95,"Are you American?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (96,"I speak Bambara");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (97,"Where is the bank?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (98,"Is it here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (99,"Is there a post office here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (100,"Where is the toilet?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (101,"My name is Mariam");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (102,"Mariam");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (103,"Madam?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (104,"How much is this orange?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (105,"Orange");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (106,"This");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (107,"This orange");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (108,"How much?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (109,"How is it? [an informal “How are you?”]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (110,"One orange");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (111,"How much is one orange?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (112,"You're welcome [app. response to thanks]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (113,"You’re welcome [broken down part by part]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (114,"CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (115,"One");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (116,"5 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (117,"Two");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (118,"Two oranges");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (119,"10 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (120,"One orange, 10 CFA");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (121,"Water");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (122,"Is that so?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (123,"Yes, that is so");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (124,"Give it to me");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (125,"Give me water");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (126,"Give me four waters");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (127,"Four");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (128,"It's all right [That's okay / enough / fine]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (129,"Please, give me one");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (130,"Take it / receive it");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (131,"[Response to a welcome]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (132,"Please, what is your name?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (133,"Four oranges");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (134,"Oranges are not here");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (135,"Okay, give me water");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (136,"Please, four waters");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (137,"That's enough, thank you");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (138,"Give me a little bit");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (139,"Go on / continue");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (140,"Please, continue");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (141,"Madam, thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (142,"Thank you very, very much!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (143,"Madam, goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (144,"Please, is there a post office here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (145,"Is there a food place here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (146,"Food");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (147,"Is there food here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (148,"This food");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (149,"Give me this food");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (150,"Three sodas");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (151,"Eat, to [verb]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (152,"I eat");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (153,"You eat");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (154,"You eat t?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (155,"Drink, to [verb]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (156,"Do you drink Coca-Cola?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (157,"You are going");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (158,"You are going to Segou");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (159,"Really? You are going to Segou?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (160,"I drink beer");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (161,"I eat a lot of t?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (162,"I like t? a lot");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (163,"It is delicious");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (164,"At the food place");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (165,"Please, I am going");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (166,"Yes, I am going to a restaurant");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (167,"I am going, and you?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (168,"Left");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (169,"It is on the left");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (170,"No, add some");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (171,"Do you like Malian food?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (172,"Do you eat t??");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (173,"Where are you going?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (174,"Are you going to the food place?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (175,"Where is it?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (176,"It’s to the right of the school");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (177,"I like tea and coffee");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (178,"I don’t like it");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (179,"I like it, I don’t like it");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (180,"Many chop bars");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (181,"The chop bar is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (182,"Are you also going to the chop bar?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (183,"I have, I don’t have");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (184,"No, no, one cedi");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (185,"I have ten pesewas");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (186,"I don’t have ten pesewas");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (187,"Ghanaian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (188,"I am Ghanaian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (189,"Yes, I am Ghanaian");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (190,"You speak Dagaare");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (191,"You speak Dagaare very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (192,"Are you Ghanaian?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (193,"Oh, you speak Dagaare!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (194,"The lorry station is there");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (195,"My name is Brenard");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (196,"I speak Dagaare");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (197,"My name is Po?we?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (198,"Po?we?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (199,"Cedi");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (200,"Pesewa");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (201,"One pesewa");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (202,"Two pesewas");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (203,"One orange, two pesewas");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (204,"Give me");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (205,"Po?naa, thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (206,"Po?naa, goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (207,"Is there a chop bar here?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (208,"Three [beer]s");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (209,"You eat fufu");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (210,"You are going to Jirapa");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (211,"Really? You are going to Jirapa?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (212,"I eat a lot of fufu");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (213,"I like fufu a lot");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (214,"At the chop bar");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (215,"No, I am going to a restaurant");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (216,"No, more");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (217,"Do you like Ghanaian food?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (218,"Do you eat fufu?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (219,"Are you going to a chop bar?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (220,"I don’t like");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (221,"I like, I don’t like");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (222,"[response to a greeting in the morning]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (223,"I am, Menye");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (224,"I");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (225,"Good morning");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (226,"I am fine");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (227,"[response to informal greeting]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (228,"Bye bye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (229,"You speak Ewe");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (230,"You speak Ewe very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (231,"I speak English");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (232,"Oh, you speak Ewe!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (233,"Is what?, ?e?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (234,"My name is Kwame");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (235,"I speak Ewe");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (236,"Thanks");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (237,"It’s fine [response to informal greeting]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (238,"My name is Ama");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (239,"Ama");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (240,"Give me water, Na tsim.");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (241,"Togbui, thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (242,"Togbui, goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (243,"You are going to Ho");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (244,"Really? You are going to Ho?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (245,"I eat a lot of akple");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (246,"I like akple a lot");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (247,"Do you eat akple?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (248,"You speak Ga");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (249,"You speak Ga very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (250,"Oh, you speak Ga!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (251,"My name is [Relevant Boy’s Name]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (252,"I speak [Target Language]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (253,"My name is [Relevant Girl’s Name]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (254,"[Relevant Girl’s Name]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (255,"My name is [Relevant Boy’s Name 1]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (256,"How is it? [informal greeting]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (257,"[response to a welcome]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (258,"Go ahead / continue");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (259,"Take / receive it");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (260,"[Relevant Title for Chief], thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (261,"[Relevant Title for Chief], goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (262,"You are going to [Relevant City]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (263,"Really? You are going to [Relevant City]?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (264,"I (first person pronoun, variation)");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (265,"You speak Gonja");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (266,"You speak Gonja very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (267,"Are you a Gonja?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (268,"Excuse me, are you a Gonja?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (269,"Oh, you speak Gonja!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (270,"Where is");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (271,"You speak Gonja well");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (272,"My name is Dramundu");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (273,"I speak Gonja");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (274,"My name is Fatima");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (275,"Fatima");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (276,"My name is Dramundu.");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (277,"You are going to Daboya");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (278,"Really? You are going to Daboya?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (279,"No, no, 1 Cedis");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (280,"I have 10 Cedis");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (281,"I don’t have 10 Cedis");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (282,"You speak Jula");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (283,"You speak Jula very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (284,"Oh, you speak Jula!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (285,"I speak Jula");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (286,"One Cedi");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (287,"2 Cedis");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (288,"One orange, 2 Cedis");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (289,"[Response to a welcome or greeting from a woman]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (290,"You are going to Wenchi");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (291,"Really? You are going to Wenchi?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (292,"I drink tea");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (293,"Yes, I am going to a chop bar");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (294,"Good morning! [To a single man]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (295,"[Response to a greeting FROM a woman]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (296,"You speak Nafaanra");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (297,"You speak Nafaanra very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (298,"Are you a(n) Nafana?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (299,"Excuse me, are you a(n) Nafana?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (300,"Oh, you speak Nafaanra!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (301,"How are you? [Afternoon]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (302,"My name is Sie");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (303,"I speak Nafaanra");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (304,"I am fine [response to How are you? In the afternoon]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (305,"My name is Yeli");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (306,"Yeli");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (307,"Good Afternoon [to a woman]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (308,"[Response to a welcome FROM a woman]");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (309,"Nana, thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (310,"Nana, goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (311,"You are going to Brodi");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (312,"Really? You are going to Brodi?");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (313,"You speak Waale");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (314,"You speak Waale very well!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (315,"Oh, you speak Waale!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (316,"My name is Seidu");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (317,"I speak Waale");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (318,"My name is Fatuma");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (319,"Fatuma");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (320,"Naa, thank you very much");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (321,"Naa, goodbye!");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (322,"You are going to Wa");
INSERT INTO phrase (ID, PHRASE_TEXT) VALUES (323,"Really? You are going to Wa?");
